# Generated by Django 4.2.7 on 2023-12-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bode',
            new_name='body',
        ),
    ]
